<a href="<?=$this->url(array('action'=>'index','id'=>null)); ?>"><?=$this->controllerTitle; ?></a> / <h4><?=$this->title; ?></h4>

<form id="formEdit" class="form-horizontal ajaxsubmit" method="POST" action="<?=$this->url(array('action'=>'form-post','id'=>$this->id));?>" source="<?=$this->url(array('action'=>'form-content','id'=>$this->id));?>">
    <div class="control-group">
        <label class="control-label" for="name"><?=$this->translate('column-group-name'); ?></label>
        <div class="controls">
            <input readonly="readonly" type="text" id="name" name="name" value="">
        </div>
    </div>
    
    <div class="control-group">
        <label class="control-label" for="access_profile_id"><?=$this->translate('column-group-access_profile_id'); ?></label>
        <div class="controls">
            <input type="hidden" id="access_profile_id" name="access_profile_id" class="span6 select2" source="access_profile" />
        </div>
    </div>

    
    <div class="form-actions">
            <button type="submit" class="btn btn-primary"><?=$this->translate('Save'); ?></button>
            <a class="btn" href="<?=$this->url(array('action'=>'index','id'=>null)); ?>"><?=$this->translate('Cancel'); ?></a>
        </div>
</form>