<a href="<?= $this->url(array('action' => 'index', 'id' => null)); ?>"><?= $this->controllerTitle; ?></a> / <h4><?= $this->title; ?></h4>

<form id="formEdit" class="form-horizontal ajaxsubmit" source="<?= $this->url(array('action' => 'form-content', 'id' => $this->id)); ?>">
    <div class="control-group">
        <label class="control-label" for="name"><?= $this->translate('column-group-name'); ?></label>
        <div class="controls">
            <input readonly="readonly" type="text" id="name" name="name" value="" readonly="readonly" disabled="disabled">
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="access_profile_id"><?= $this->translate('column-group-access_profile_id'); ?></label>
        <div class="controls">
            <input type="hidden" id="access_profile_id" name="access_profile_id" class="span6 select2" source="access_profile" readonly="readonly" disabled="disabled"/>
        </div>
    </div>

    <div class="form-actions">
	<a class="btn" href="<?= $this->url(array('action' => 'index', 'id' => null)); ?>"><?= $this->translate('Back'); ?></a>
    </div>
</form>