<h4><?= $this->translate('Meeting Rooms Management'); ?></h4>

<div class="pull-left">
    <?
    if (IMDT_Util_Acl::getInstance()->isAllowed('rooms', 'insert')):
    ?>
        <a class="btn" href="/ui/rooms/new"><i class="icon-plus-sign"></i> <?= $this->translate('New meeting room'); ?></a>
    <?
    endif;
    ?>
    <?
    if (IMDT_Util_Acl::getInstance()->isAllowed('rooms', 'delete')):
    ?>
    <a class="btn" onclick="deleteAllSelected('#records','/ui/rooms/delete/id/'); return false;"><i class="icon-trash"></i> <?= $this->translate('Delete selected'); ?></a>
    <div class="btn-group">
        <a class="btn" onclick="selectAll('#records'); return false;"><i class="icon-ok"></i> <?= $this->translate('Select all'); ?></a>
        <button class="btn dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li><a href="#" onclick="unselectAll('#records'); return false;"><i class="icon-remove"></i> <?= $this->translate('Unselect all'); ?></a></li>
        </ul>
    </div>
    <?
    endif;
    ?>
</div>

<div class="pull-right">
    <form id="frmMainFilter" class="form-inline" method="GET">
        
        <?
        $paramName = 'main_date_start';
        $conditionValue = 'b';
        $mainValue = '';
        $mainUntil = '';
        
        foreach($this->parameters['q'] as $currParam) {
            if($currParam['n'] == $paramName) {
                $mainValue = $currParam['v'];
                
                if($conditionValue == 'b' && isset($currParam['u'])) {
                    $mainUntil = $currParam['u'];
                }
            }
        }
        
        if(strlen($mainValue) > 0) $mainValue = Imdt_Util_Date::filterDatetimeToCurrentLang($mainValue, false);
        if(strlen($mainUntil) > 0) $mainUntil = Imdt_Util_Date::filterDatetimeToCurrentLang($mainUntil, false);
        
        ?>
        
    	<div class="row-filter" style="float:left;">
    	    <!--
    	    <input type="hidden" class="column" value="date_start" column-type="date" />
    	    -->
    	    <div class="filter-values">
    	        <!--
        		<input type="hidden" class="condition" value="b" />
        		-->
        		<label class="text" for="minDate">
                    <?=$this->translate('column-access_log-create_date'); ?> <?=$this->translate('between'); ?> 
                    <div class="input-append datetime" copy-to="#frmAdvFilter div.filter-values.main_date_start div.datetime.first">
                        <input id="minDate" type="text" class="input-small value sdatetime" data-format="<?=$this->translate('dateFormat-datetimepicker'); ?>" value="<?=$mainValue; ?>">
                         <span class="add-on"><i data-time-icon="icon-time" data-date-icon="icon-calendar"></i></span>
                    </div>
                </label>
                <label class="text" for="maxDate">
                     <?=$this->translate('and'); ?>
                     <div class="input-append datetime" copy-to="#frmAdvFilter div.filter-values.main_date_start div.datetime.second">
                        <input id="maxDate" type="text" class="input-small value_2 sdatetime" data-format="<?=$this->translate('dateFormat-datetimepicker'); ?>" value="<?=$mainUntil; ?>">
                        <span class="add-on"><i data-time-icon="icon-time" data-date-icon="icon-calendar"></i></span>
                    </div>
                </label>
            </div>
    	</div>
        
    	<div class="" style="float:left; margin-left:4px;">
    	    <button class="btn" type="button" onclick="applyFilter('#records');"><i class="icon-search"></i> <?= $this->translate('Search'); ?>!</button>
    	    <button class="btn" type="button" id="advSearch" modal-open="#modalAdvSearch" style=""><?= $this->translate('Advanced search'); ?></button>
    	</div>
    </form>
</div>

<table class="table table-striped dtables rows-selectable" id="records" ajaxsource="<?= $this->url($this->tableSource, null, true); ?>?<?= $this->parametersString; ?>" ajaxsource-nofilters="<?= $this->url($this->tableSource, null, true); ?>" uri-nofilters="<?= $this->url($this->uriPage, null, true); ?>">
    <thead>
        <tr>
            <th style="width:5px; text-align:center;" class="no-sort no-search"></th>
            <th><?= $this->translate('column-meeting_room-name'); ?></th>
            <th class="no-search sort-desc" data-format="datetime" data-column="2"><?= $this->translate('column-meeting_room-date_start'); ?></th>
            <th class="no-search"><?= $this->translate('column-meeting_room-date_end'); ?></th>
            <th style="width:160px; text-align:center;" class="no-sort no-search"><?= $this->translate('Actions'); ?></th>
        </tr>
    </thead>
    <tbody>
	<!--
        <tr id="loading">
            <td colspan="5">Obtendo salas</td>
        </tr>
	-->
    </tbody>
</table>

<div class="row-fluid">
    <div class="span7">
        <form class="form-inline">
            <div class="btn-group">
                <button class="btn dropdown-toggle btn-export" data-toggle="dropdown">
		    <?= $this->translate('Export'); ?>
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li><a export="records" href-origin="<?= $this->url($this->uriExport, null, true); ?>" href="<?= $this->url($this->uriExport, null, true); ?>?<?= $this->parametersString; ?>">CSV</a></li>
                    <li><a export="records" href-origin="<?= $this->url($this->uriExportPdf, null, true); ?>" href="#" data-href="<?= $this->url($this->uriExportPdf, null, true); ?>?<?= $this->parametersString; ?>">PDF</a></li>
                </ul>
            </div>
	    <?
	    if (IMDT_Util_Acl::getInstance()->isAllowed('rooms', 'insert')):
	    ?>
            <button class="btn" id="csvImport"><?= $this->translate('Import CSV'); ?></button>
	    <?
	    endif;
	    ?>
        </form>
    </div>
</div>

<div id="modalAdvSearch" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	<h3 id="myModalLabel"><?= $this->translate('Advanced search'); ?></h3>
    </div>
    <div class="modal-body">
	<form id="frmAdvFilter" class="form-vertical" onsubmit="applyFilter('#records','#modalAdvSearch'); $('#modalAdvSearch').modal('hide'); return false;" source="<?=$this->url(array('action'=>'adv-search-filter'));?>">
	    <?= $this->formFilters($this->filters, $this->parameters); ?>
	</form>
    </div>
    <div class="modal-footer">
	<button class="btn" data-dismiss="modal" aria-hidden="true"><?= $this->translate('Close'); ?></button>
	<button class="btn btn-primary" onclick="applyFilter('#records'); $('#modalAdvSearch').modal('hide');"><?= $this->translate('Search now'); ?></button>
    </div>
</div>

<div id="modalDuplicate" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <form id="formDuplicate" action="/ui/rooms/duplicate/">
    	<div class="modal-header">
    	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    	    <h3 id="myModalLabel"><?= $this->translate('Duplicate'); ?></h3>
    	</div>
    	<div class="modal-body">
    	    <input type="hidden" name="duplicated_id" id="duplicatedId" />
                <div class="control-group">
                    <label class="control-label" for="duplicateName"><?= $this->translate('column-meeting_room-name'); ?></label>
                    <input type="text" class="input-block-level" name="name" id="duplicateName" />
                </div>
                <div class="control-group">
                    <label class="control-label" for="duplicateUrl"><?= $this->translate('column-meeting_room-url'); ?></label>
    		        <input type="text" class="input-block-level" name="url" id="duplicateUrl" />
                </div>
    	</div>
    	<div class="modal-footer">
    	    <div class="hide alert alert-error" style="text-align:center;"><?= $this->translate('Alert'); ?></div>
    	    <span class="loading hide">
    		<div style="text-align:center;"><?= $this->translate('Saving'); ?></div>
    		<div class="progress progress-striped active"><div class="bar" style="width: 100%;"></div></div>
    	    </span>
    	    <span class="save-buttons">
    		<button type="submit" class="btn btn-primary"><?= $this->translate('Duplicate now'); ?></button>
    		<button class="btn" data-dismiss="modal" aria-hidden="true"><?= $this->translate('Close'); ?></button>
    	    </span>
    	    <span class="success-buttons hide">
    		<div class="alert alert-success" style="text-align:center;"><?= $this->translate('Data was saved successfully'); ?></div>
    		<button id="btn_edit_copy" class="btn btn-primary"><?= $this->translate('Edit copy'); ?></button>
    		<button id="btn_close_copy" class="btn"><?= $this->translate('Close'); ?></button>
    	    </span>
    	</div>
    </form>
</div>

<div id="modalCsvImport" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel"><?= $this->translate('Import CSV'); ?></h3>
    </div>
    <div class="modal-body">
        <form id="frmCsvImport" class="form-vertical" method="post" enctype="multipart/form-data" data-import-url="<?=$this->url(array('action'=>'import'));?>">
            <span class="btn btn-inverse fileinput-button">
                <i class="glyphicon glyphicon-plus"></i>
                <span><?=$this->translate('Selec file');?></span>
                <input id="fileupload" type="file" name="files[]" data-url="/ui/upload/post"/>
            </span>
        </form>
	<div id="fileContainer"></div>
	<div class="alert alert-info hidden">
	    <div class="alert-message processing">
		<img src="/resources/img/ajax-loader.gif" />  <?=$this->translate('Processing...'); ?>
	    </div>
	    <div class="alert-message import-result"></div>
	</div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><?= $this->translate('Close'); ?></button>
        <button class="btn btn-primary" onclick="csvUpload(this);" disabled="disabled" data-widget="import"><?= $this->translate('Import'); ?></button>
    </div>
</div>