<h4><?=$this->translate('Closed Meetings'); ?></h4>

<div class="pull-right">
    <form id="frmFilter" class="form-inline" method="GET">
	<div class="row-filter" style="float:left;">
	    <input type="hidden" class="column" value="date_start" column-type="date" />
	    <input type="hidden" class="condition" value="b" />

	    <label class="text" for="minDate">
		<?=$this->translate('column-meeting_room-date_start-filter'); ?> <?=$this->translate('between'); ?> 
		<div class="input-append datepick">
		    <input id="minDate" type="text" class="input-small value_date" data-format="<?=$this->translate('dateFormat-datepicker'); ?>" value="<?=isset($this->parameters['date_start']) ? IMDT_Util_Date::filterDateToCurrentLang($this->parameters['date_start']) : ''; ?>">
		    <span class="add-on"><i data-time-icon="icon-time" data-date-icon="icon-calendar"></i></span>
		</div>
	    </label>
	    <label class="text" for="maxDate">
		 <?=$this->translate('and'); ?>
		 <div class="input-append datepick">
		    <input id="maxDate" type="text" class="input-small value_date_2" data-format="<?=$this->translate('dateFormat-datepicker'); ?>" value="<?=isset($this->parameters['date_start_2']) ? IMDT_Util_Date::filterDateToCurrentLang($this->parameters['date_start_2']) : ''; ?>">
		    <span class="add-on"><i data-time-icon="icon-time" data-date-icon="icon-calendar"></i></span>
		</div>
	    </label>
	</div>

	<div class="" style="float:left; margin-left:4px;">
	    <button class="btn" type="button" onclick="applyFilter('#records');"><i class="icon-search"></i> <?=$this->translate('Refresh'); ?>!</button>
	</div>
    </form>
</div>

<table class="table table-striped dtables" id="records" ajaxsource="<?=$this->url(array_merge($this->tableSource,$this->parameters),null,true);?>" ajaxsource-nofilters="<?=$this->url($this->tableSource,null,true);?>">
    <thead>
        <tr>
            <th><?=$this->translate('column-meeting_room-name'); ?></th>
            <th class="no-search"><?=$this->translate('column-meeting_room-date_start'); ?></th>
            <th class="no-search"><?=$this->translate('column-meeting_room-date_end'); ?></th>
            <th nowrap="nowrap" class="no-sort"><?=$this->translate('Actions'); ?></th>
        </tr>
    </thead>
    <tbody></tbody>
</table>