<h4><?= $this->translate('Meeting Rooms Access'); ?></h4>

<div class="row-fluid">
    <div class="span9">
        <form class="form-inline" method="get">
            <label class="text" for="minDate">
                <?= $this->translate('column-meeting_room-date_start-filter'); ?> <?= $this->translate('between'); ?>
                <div class="input-append datepick">
                    <input name="date_start" id="minDate" type="text" class="input-small value_date" data-format="<?= $this->translate('dateFormat-datepicker'); ?>" value="<?= isset($this->parameters['date_start']) ? IMDT_Util_Date::filterDateToCurrentLang($this->parameters['date_start']) : ''; ?>">
                    <span class="add-on"><i data-time-icon="icon-time" data-date-icon="icon-calendar"></i></span>
                </div>
            </label>
            <label class="text" for="maxDate">
                <?= $this->translate('and'); ?>
                <div class="input-append datepick">
                    <input name="date_start_2" id="maxDate" type="text" class="input-small value_date_2" data-format="<?= $this->translate('dateFormat-datepicker'); ?>" value="<?= isset($this->parameters['date_start_2']) ? IMDT_Util_Date::filterDateToCurrentLang($this->parameters['date_start_2']) : ''; ?>">
                    <span class="add-on"><i data-time-icon="icon-time" data-date-icon="icon-calendar"></i></span>
                </div>
                <button class="btn" type="submit"><i class="icon-search"></i> <?= $this->translate('Refresh'); ?>!</button>
            </label>
            <input type="hidden" name="date_start_c" value="b"/>
        </form>
    </div>
    <div class="span3">
        <a href="/ui/my-rooms/all" class="btn pull-right"><?= $this->translate('All Meetings'); ?> </a>
    </div>
</div>

<div class="row-fluid">
    <div class="span9">
        <div class="row-fluid">
            <?
            if(count($this->collection) > 0):
            $i = 0;
            foreach ($this->collection as $room):

            if (isset($room['show_actions']) && ($room['show_actions'] == true)):
            ?>
            <div class="btn-group">
                <a class="btn btn-large <?= $room['button_class']; ?>" href="/<?= $room['url']; ?>">
                    <?= $room['name']; ?>
                    <br/>
                    <span style="font-size:12px;"><?= IMDT_Util_Date::dateInformal(strtotime($room['date_start'])); ?>, <?= date('H:i', strtotime($room['date_start'])); ?></span>
                </a>
                <a class="btn btn-large <?= $room['button_class']; ?> dropdown-toggle" data-toggle="dropdown" style="height:42px;">
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/<?= $room['url']; ?>"><?= $this->translate('Access Meeting room'); ?></a></li>

                    <? if(in_array($room['user_profile_in_meeting'],array(BBBManager_Config_Defines::$ROOM_ADMINISTRATOR_PROFILE,BBBManager_Config_Defines::$ROOM_MODERATOR_PROFILE))): ?>
                    <li><a href="<?= $this->url(array('controller' => 'rooms', 'action' => 'manage-attendees', 'id' => $room['meeting_room_id'])); ?>"><?= $this->translate('Configure'); ?></a></li>
                    <? endif; ?>
                    <li><a href="#" class="send-invitatios" data-meeting-room-id="<?= $room['meeting_room_id']; ?>" form-data=''><?= $this->translate('Send invitations'); ?></a></li>
                </ul>
            </div>

            <div id="modalInvite-<?= $room['meeting_room_id']; ?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <form id="form-invite-<?= $room['meeting_room_id']; ?>" data-form-invite="form-invite" class="form-vertical no-loading no-reset load-onclick" action="<?= $this->url(array('controller' => 'rooms', 'action' => 'form-invite-post')); ?>" source="<?= $this->url(array('controller' => 'rooms', 'action' => 'form-invite-content', 'id' => $room['meeting_room_id'])); ?>">
                    <input type="hidden" name="meeting_room_id" id="meeting_room_id" value="<?= $room['meeting_room_id']; ?>" />
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3 id="myModalLabel"><?= $this->translate('Send invitations'); ?></h3>
                    </div>
                    <div class="modal-body">
                        <div class="row-fluid">
                            <div class="span3">
                                <div class="control-group">
                                    <label class="control-label" for="invite_template_id"><?= $this->translate('column-invite_template-name'); ?></label>
                                    <input type="hidden" id="invite_template_id-<?= $room['meeting_room_id']; ?>" name="invite_template_id" class="span12 select2 invite_template_id" source="templates" data-meeting-room-id="<?= $room['meeting_room_id']; ?>"/>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="subject"><?= $this->translate('column-invite_template-subject'); ?></label>
                                    <input type="text" class="input-block-level" id="subject" name="subject" />
                                </div>
                            </div>
                            
                            <div class="span9">
                                <div class="control-group">
                                    <label class="control-label" for="body"><?= $this->translate('column-invite_template-body'); ?></label> <br clear="all" />
                                    <textarea class="input-block-level" name="body" id="body-<?= $room['meeting_room_id']; ?>" rows="8" class="ckeditor"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <div style="text-align:left;">
                            <table>
                                <tr>
                                    <td style="padding:0 6px;"><?= $this->translate('Available Placeholders'); ?>:</td>
                                    <td style="padding:0 6px;"><?= $this->translate('__ROOM_START__'); ?></td>
                                    <td style="padding:0 6px;"><?= $this->translate('__ROOM_END__'); ?></td>
                                    <td style="padding:0 6px;"><?= $this->translate('__ROOM_NAME__'); ?></td>
                                    <td style="padding:0 6px;"><?= $this->translate('__ROOM_URL__'); ?></td>
                                    <td style="padding:0 6px;"><?= $this->translate('__ROOM_PRESENTER__'); ?></td>
                                </tr>
                            </table>
                        </div>
                        <div class="hide alert alert-error" style="text-align:center;"><?= $this->translate('Alert'); ?></div>
                        <span class="save-buttons">
                            <button type="submit" class="btn btn-primary"><?= $this->translate('Send now'); ?></button>
                            <button class="btn" data-dismiss="modal" aria-hidden="true"><?= $this->translate('Close'); ?></button>
                        </span>
                        <span class="success-buttons hide">
                            <div class="alert alert-success" style="text-align:center;"></div>
                            <button class="btn" data-dismiss="modal" aria-hidden="true"><?= $this->translate('Close'); ?></button>
                            <button type="btn" class="btn btn-primary hidden confirm"><?= $this->translate('Confirm'); ?></button>
                        </span>
                        <span class="loading hide">
                            <div style="text-align:center;"><?= $this->translate('Invitations are being sent'); ?></div>
                            <div class="progress progress-striped active"><div class="bar" style="width: 100%;"></div></div>
                        </span>
                    </div>
                </form>
            </div>

            <?
            else:
            ?>
            <div class="span4">
                <a class="btn btn-large <?= $room['button_class']; ?>" href="/<?= $room['url']; ?>" >
                    <?= $room['name']; ?> 
                    <br/>
                    <span style="font-size:12px;"><?= IMDT_Util_Date::dateInformal(strtotime($room['date_start'])); ?>, <?= date('H:i', strtotime($room['date_start'])); ?></span>
                </a>
            </div>
            <?
            endif;
            ?>
            <?
            $i++;

            if($i == 3):
            $i = 0;
            ?>
        </div>
        <div class="clearfix" style="height:30px;"></div>
        <div class="row-fluid">
            <?
            endif;

            endforeach;
            endif;
            ?>
        </div>

        <div class="clearfix" style="height:30px;"></div>
    </div>
</div>