<h4>Gravações</h4>

<form class="form-inline">
    <div class="pull-left">
        <label class="text" for="dataini">

             Gravações Entre 
             <div class="input-append datepick">
                <input type="text" class="input-small" data-format="dd/MM/yyyy"> 
                <span class="add-on "><i data-time-icon="icon-time" data-date-icon="icon-calendar"></i></span>
            </div>
        </label>
        <label class="text" for="datafinal">
             e 
             <div class="input-append datepick">
                 <input type="text" class="input-small" data-format="dd/MM/yyyy">
                 <span class="add-on"><i data-time-icon="icon-time" data-date-icon="icon-calendar"></i></span>
            </div>
        </label>
    </div>
    <div class="pull-right">
        <button class="btn" type="button"><i class="icon-search"></i> Pesquisar!</button>
        <button class="btn" type="button">Pesquisa Avançada</button>
    </div>
</form>

<table class="table table-striped dtables">
    <thead>
        <tr>
            <th>Gravação</th>
            <th>Realizado Em</th>
            <th class="no-sort">Ações</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td width="100%">Treinamento Liderando Equipes</td>
            <td nowrap="nowrap" width="100%">01/01/2013 15:00 </td>
            <td nowrap="nowrap">
                <a href="#" class="btn btn-mini" data-toggle="tooltip" title="Visualizar"><i class="icon-eye-open"></i></a>
            </td>
        </tr>
        <tr>
            <td width="100%">Treinamento Liderando Equipes - Módulo 2</td>
            <td nowrap="nowrap" width="100%">01/01/2013 15:00 </td>
            <td nowrap="nowrap">
                <a href="#" class="btn btn-mini" data-toggle="tooltip" title="Visualizar"><i class="icon-eye-open"></i></a>
            </td>
        </tr>
        <tr>
             <td width="100%">Uso do BBB no MP/RS</td>
            <td nowrap="nowrap" width="100%">01/01/2013 15:00 </td>
            <td nowrap="nowrap">
                <a href="#" class="btn btn-mini" data-toggle="tooltip" title="Visualizar"><i class="icon-eye-open"></i></a>
            </td>
        </tr>
    </tbody>
</table>

<div class="row-fluid">
    <div class="span7">
        <form class="form-inline">
            <select>
                <option>Exibir 10 por página</option>
            </select>
            <div class="btn-group">
                <button class="btn">Exportar</button>
                <button class="btn dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li><a href="#">CSV</a></li>
                    <li><a href="#">PDF</a></li>
                </ul>
            </div>
        </form>
    </div>
    
    <div class="span5">
        <div class="pagination pull-right" style="margin:0px;">
            <ul>
                <li><a href="#">Ant.</a></li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">Prox.</a></li>
            </ul>
        </div>    
    </div>
</div>

