<h4><?=$this->translate('View Recording'); ?></h4>

<div class="row-fluid">
    <div class="span7">
        <select id="recordingSelection" class="input-block-level select2">
<?php
    foreach($this->recordings as $recording):
?>
<option data-record-id="<?=$recording['record_id'];?>" value="<?=$recording['playback_url'];?>"><?=$recording['name'] . ' (' . date('d/m/Y H:i:s', strtotime($recording['date_start'])) . ' - ' . $recording['duration'] . ')';?></option>
<?
    endforeach;
?>
        </select>
    </div>
    <div class="span5">
        <div class="btn-group" id="viewRecordingTagSelector">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">Tags <span class="caret"></span></a>
            <ul class="dropdown-menu"></ul>
        </div>
        <a class="btn pull-right" href="<?=$this->backUrl;?>">Voltar</a>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <iframe name="playback-frame" frameborder="0" width="100%" height="900px" src="<?=$this->firstRecording['playback_url'];?>"></iframe>
    </div>
</div>

