<div class="row-fluid text-center">
    <div class="span12">
	<img src="/resources/img/logo.png" />
	<h4>
            <a href="<?=IMDT_Util_Config::getInstance()->get('web_base_url');?>"><?=BBBManager_Util_Skinning::getInstance()->get('company_name') . ' - ' . BBBManager_Util_Skinning::getInstance()->get('system_title');?></a>
        </h4>
    </div>
</div>

<div class="innerContainer">
    <div class="row-fluid">
	<div class="span12">
	    <h2 class="form-signin-heading"><?= $this->translate('Access meeting room'); ?> "<?= $this->room['name']; ?>"</h2>
	    <input type="hidden" id="roomId" value="<?= $this->room['meeting_room_id']; ?>" />
	    <p>
		<?= $this->translate('The access of this room is public'); ?>.
	    </p>
	    <p>
		<?= $this->translate('If you have a login credential, we suggest using it, to use all system resources.'); ?>.
	    </p>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span6 pull-left">
	    <h4><?= $this->translate('Authenticated Access'); ?></h4>
	    <form class="form-signin" method="post" action="/login/auth/auth">
		<input type="text" class="input-block-level" placeholder="<?= $this->translate('User'); ?>" name="user">
		<input type="password" class="input-block-level" placeholder="<?= $this->translate('Password'); ?>" name="password">
		<input type="hidden" name="meetingRoomId" value="<?=$this->room['meeting_room_id'];?>">
		<button class="btn btn-primary" type="submit"><?= $this->translate('Join'); ?></button>
	    </form>
	</div>
	<div class="span6 pull-right">
	    <h4><?= $this->translate('Public Access (Mozilla Persona)'); ?></h4>
	    <a href="#" class="persona-button persona-signin"><span><?= $this->translate('Sign in with Persona'); ?></span></a>
	</div>
    </div>
</div>


<div class="modal hide fade" id="extraInfo">
    <div class="modal-header">
	<a class="close" data-dismiss="modal" style="right:0px;">×</a>
	<h3><?= $this->translate('Alert'); ?></h3>
    </div>
    <div class="modal-body">
	<div class="alert alert-info">
	    Para efetuar o seu login, preencha os dados abaixo e clique no botão Entrar.
	</div>
	<div class="control-group" id="extraInfo">
	    <label class="control-label" for="name">Informe seu nome completo</label>
	    <div class="controls">
		<input type="text" name="name" id="name" class="input-block-level"/>
	    </div>
	    <input type="hidden" name="assertion" id="assertion"/>
	</div>
    </div>
    <div class="modal-footer">
	<button class="btn btn-primary" aria-hidden="true" id="btnGo"><?= $this->translate('Entrar'); ?></button>
	<button class="btn" data-dismiss="modal" aria-hidden="true"><?= $this->translate('Close'); ?></button>
    </div>
</div>