<div class="row-fluid text-center">
    <div class="span12">
	<img src="/resources/img/logo.png" />
	<h4>Web Conference</h4>
    </div>
</div>

<div class="innerContainer">
    <div class="row-fluid">
	<div class="span12">
	    <h2 class="form-signin-heading">Acesso à sala "<?= $this->room['name']; ?>"</h2>
	    <input type="hidden" id="roomId" value="<?= $this->room['meeting_room_id']; ?>" />
	    <p>
		O acesso desta sala é público.
	    </p>
	    <p>
		Caso você tenha um login, sugerimos utilizá-lo, para usar todos os recursos do sistema.
	    </p>
	</div>
    </div>
    <div class="row-fluid">
	<div class="span6 pull-left">
	    <h4>Acesso Autenticado</h4>
	    <form class="form-signin" method="post" action="/login/auth/auth">
		<input type="text" class="input-block-level" placeholder="<?= $this->translate('User'); ?>" name="user">
		<input type="password" class="input-block-level" placeholder="<?= $this->translate('Password'); ?>" name="password">
		<input type="hidden" name="meetingRoomId" value="<?=$this->room['meeting_room_id'];?>">
		<button class="btn btn-primary" type="submit"><?= $this->translate('Join'); ?></button>
	    </form>
	</div>
	<div class="span6 pull-right">
	    <h4>Acesso Público (Mozilla Persona)</h4>
	    <a href="#" class="persona-button persona-signin"><span>Sign in with Persona</span></a>
	</div>
    </div>
</div>


<div class="modal hide fade" id="extraInfo">
    <div class="modal-header">
	<a class="close" data-dismiss="modal" style="right:0px;">×</a>
	<h3><?= $this->translate('Alert'); ?></h3>
    </div>
    <div class="modal-body">
	<div class="alert alert-info">
	    Para efetuar o seu login, preencha os dados abaixo e clique no botão Entrar.
	</div>
	<div class="control-group" id="extraInfo">
	    <label class="control-label" for="name">Informe seu nome completo</label>
	    <div class="controls">
		<input type="text" name="name" id="name" class="input-block-level"/>
	    </div>
	    <input type="hidden" name="assertion" id="assertion"/>
	</div>
    </div>
    <div class="modal-footer">
	<button class="btn btn-primary" aria-hidden="true" id="btnGo"><?= $this->translate('Entrar'); ?></button>
	<button class="btn" data-dismiss="modal" aria-hidden="true"><?= $this->translate('Close'); ?></button>
    </div>
</div>