<?= $this->renderMessages(); ?>

<?
if (count($this->collection) > 0):
    ?>
    <table class="table table-striped">
        <thead>
            <tr>
                <th><?=$this->translate('Meeting Room');?></th>
                <th nowrap="nowrap"><?=$this->translate('Start time');?></th>
                <th nowrap="nowrap" class="no-sort"><?=$this->translate('Access');?></th>
            </tr>
        </thead>
        <tbody>
	    <?
	    foreach ($this->collection as $publicRoom):
		?>
	        <tr>
	            <td width="100%"><?= $publicRoom['name']; ?></td>
	            <td nowrap="nowrap"><?= date($this->translate('dateTimeFormat-php'), strtotime($publicRoom['date_start'])); ?></td>
	            <td style="text-align:center;">
			<a class="btn" href="<?= $this->url(array('action' => 'enter', 'id' => $publicRoom['meeting_room_id'])); ?>" title="<?=$this->translate('Access');?>" data-toggle="tooltip" data-original-title="<?=$this->translate('Access');?>"><i class="icon-eye-open"></i></a>
		    </td>
	        </tr>
		<?
	    endforeach;
	    ?>
        </tbody>
    </table>
    <?
else:
    ?>
    <div class="alert alert-error">
        <div class="alert-message">
	    <?=$this->translate('There is no running or waiting public meeting rooms for the moment.');?>
	</div>
    </div>
<?
endif;
?>