<h4>Administração de Skinning</h4>
<form class="form-horizontal">
    <div class="row-fluid">
        <div class="span7">
            <div class="control-group">
                <label class="control-label" for="instituicao">Instituição</label>
                <div class="controls">
                    <input type="text" id="instituicao" class="span5">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="logotipo">Logotipo (largura x altura)</label>
                <div class="controls">
                    <input type="file"  id="logotipo">
                </div>
            </div>
        </div>
        <div class="span5">
            <p>Preview do logotipo: </p>
            <img src="/resources/img/imagem.jpg" class="img-polaroid" />
        </div>
    </div>
    <div class="form-actions pull-right span12">
        <button class="btn btn-primary">Salvar</button>
        <a class="btn" href="/ui/index">Cancelar</a>
    </div>
</form>

