<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html dir="ltr" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta content="text/html; charset=utf-8" http-equiv="content-type">        
</head>
<body style="padding: 20px; background-color: rgb(238, 238, 238);">
    <div style="border: 1px solid rgb(215, 215, 215); width: 600px; margin: 0px auto; background-color: rgb(255, 255, 255); border-radius: 5px 5px 5px 5px;">
        <div style="padding: 20px;">
            <a style="float: left; margin-right: 20px;" href="<?=$this->serverUrl()?>" target="_blank"><img width="250" src="<?=$this->serverUrl()?>/resources/img/logo.png" alt=""></a>
            <h1 style="font-family: Verdana; font-size: 20px; margin: 17px 0px; font-weight: normal; color: rgb(37, 37, 37);">
                <?= empty($this->title) ? 'Contato Através do Site' : $this->title ?>
            </h1>
            <?
                if(! empty($this->description)):
            ?>
            <p style="font-family: Verdana; font-size: 12px; margin: 0px; color: rgb(37, 37, 37); text-align: justify;">
                    <?= $this->description ?>
            </p>
            <?
                endif;
            ?>              