<?=$this->doctype();?>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="pt-br" prefix="og: http://ogp.me/ns#"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="pt-br" prefix="og: http://ogp.me/ns#"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="pt-br" prefix="og: http://ogp.me/ns#"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="pt-br" prefix="og: http://ogp.me/ns#">
<!--<![endif]-->
    <head>
        <?= $this->headTitle();?>
        <?= $this->headMeta();?>
        <?= $this->Jquery()->setRenderMode(ZendX_JQuery::RENDER_STYLESHEETS);?>		
        <?= $this->headLink();?>		
        <script src="/resources/js/modernizr/modernizr-2.6.2.min.js" type="text/javascript"></script>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    
                    <a class="brand" href="<?=IMDT_Util_Config::getInstance()->get('web_base_url');?>"><?=  BBBManager_Util_Skinning::getInstance()->get('company_name');?> -  <?=  BBBManager_Util_Skinning::getInstance()->get('system_title');?></a>
                    
                    <ul class="nav pull-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=sprintf($this->translate('Logged in as %s'),IMDT_Util_Auth::getInstance()->get('full_name')); ?><b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/ui/users/edit-me"><i class="icon-user"></i> <?= $this->translate('My profile'); ?></a></li>
                                <li class="divider"></li>
                                <li><a href="/login/auth/logout"><i class="icon-off"></i> <?= $this->translate('Logout'); ?></a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row-fluid">
                
	<?
        
            $hideMenu = IMDT_Util_Auth::getInstance()->get('systemUser');
            $hideMenu = $hideMenu | (Zend_Registry::isRegistered('recordingVisualization') && (Zend_Registry::get('recordingVisualization') == true));
        
	    if($hideMenu):
	?>
                <div class="span12">
                    <?=$this->renderMessages();?>
                    <?=$this->layout()->content;?>
                </div><!--/span-->
	<?
	    else:
	?>
                <div class="span3">
		    <?=$this->renderMenu($this->currentUrl);?>
                </div><!--/span-->
                <div class="span9">
                    <?=$this->renderMessages();?>
                    <?=$this->layout()->content;?>
                </div><!--/span-->
	<?
	    endif;
	?>
            </div><!--/row-->
            <hr>
            <footer>
              <p>&nbsp;</p>
            </footer>
        </div><!--/.fluid-container-->
        <?= $this->Jquery()->setRenderMode(ZendX_JQuery::RENDER_LIBRARY|ZendX_JQuery::RENDER_SOURCES|ZendX_JQuery::RENDER_JQUERY_ON_LOAD|ZendX_JQuery::RENDER_JAVASCRIPT);?>
        <?= $this->headScript();?>
        
        <div class="modal hide fade" id="confirm-dialog">
			<div class="modal-header">
				<a class="close" data-dismiss="modal">×</a>
				<h3><?= $this->translate('Confirm'); ?></h3>
			</div>
			<div class="modal-body">
				&nbsp;
			</div>
			<div class="modal-footer">
				<a href="#" class="btn btn-danger"><?= $this->translate('Ok'); ?></a>
				<a href="#" class="btn btn-cancel" data-dismiss="modal"><?= $this->translate('Cancel'); ?></a>
			</div>
		</div>
		
		<div class="modal hide" id="wait-dialog" data-backdrop="static" data-keyboard="false">
			<div class="modal-header">
				<h3><?= $this->translate('Wait'); ?></h3>
			</div>
			<div class="modal-body">
				<div class="progress progress-striped active"><div class="bar" style="width: 100%;"></div></div>
				<div class="text" style="width:100%; text-align:center;"><?= $this->translate('Content is being loaded.'); ?></div>
			</div>
		</div>
        
        <div class="modal hide fade" id="alert-dialog">
			<div class="modal-header">
				<a class="close" data-dismiss="modal" style="right:0px;">×</a>
				<h3><?= $this->translate('Alert'); ?></h3>
			</div>
			<div class="modal-body">
				&nbsp;
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true"><?= $this->translate('Close'); ?></button>
			</div>
		</div>
        
    </body>
</html>