<?=$this->doctype();?>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="pt-br" prefix="og: http://ogp.me/ns#"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="pt-br" prefix="og: http://ogp.me/ns#"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="pt-br" prefix="og: http://ogp.me/ns#"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="pt-br" prefix="og: http://ogp.me/ns#">
<!--<![endif]-->
    <head>
        <?= $this->headTitle();?>
        <?= $this->headMeta();?>
        <?= $this->Jquery()->setRenderMode(ZendX_JQuery::RENDER_STYLESHEETS);?>		
        <?= $this->headLink();?>		
        <script src="/resources/js/modernizr/modernizr-2.6.2.min.js" type="text/javascript"></script>
    </head>
    <body>
        <div class="container">
            <div class="row-fluid">
		<div class="span12">
		    <?=$this->renderMessages();?>    
		</div>
            </div><!--/row-->
	    <?=$this->layout()->content;?>
        </div><!--/.container-->
	
	<div class="modal hide" id="wait-dialog" data-backdrop="static" data-keyboard="false">
	    <div class="modal-header">
		<h3><?= $this->translate('Wait'); ?></h3>
	    </div>
	    <div class="modal-body">
		<div class="progress progress-striped active"><div class="bar" style="width: 100%;"></div></div>
		<div class="text" style="width:100%; text-align:center;"><?= $this->translate('Content is being loaded.'); ?></div>
	    </div>
	</div>

	<div class="modal hide fade" id="alert-dialog">
	    <div class="modal-header">
		<a class="close" data-dismiss="modal" style="right:0px;">×</a>
		<h3><?= $this->translate('Alert'); ?></h3>
	    </div>
	    <div class="modal-body">
		&nbsp;
	    </div>
	    <div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true"><?= $this->translate('Close'); ?></button>
	    </div>
	</div>
        <?= $this->Jquery()->setRenderMode(ZendX_JQuery::RENDER_LIBRARY|ZendX_JQuery::RENDER_SOURCES|ZendX_JQuery::RENDER_JQUERY_ON_LOAD|ZendX_JQuery::RENDER_JAVASCRIPT);?>
        <?= $this->headScript();?>
    </body>
</html>