<a href="<?=$this->url(array('action'=>'index','id'=>null)); ?>"><?=$this->controllerTitle; ?></a> / <h4><?=$this->title; ?></h4>

<form id="formEdit" class="form-horizontal ajaxsubmit" method="POST" action="<?=$this->url(array('action'=>'form-post','id'=>$this->id));?>" source="<?=$this->url(array('action'=>'form-content','id'=>$this->id));?>">
    
    <? if($this->id != 'new'): ?>    
    <div class="control-group">
        <label class="control-label" for="access_profile_id"><?=$this->translate('column-user-auth_mode_id'); ?></label>
        <div class="controls">
            <input type="hidden" id="auth_mode_id" name="auth_mode_id" class="span6 select2" source="auth_mode" disabled="disabled" readonly="readonly" />
	    <input type="hidden" id="auth_mode_id_hidden" name="auth_mode_id" source="auth_mode"  />
        </div>
    </div>
    <?
	else:
    ?>
	<input type="hidden" id="auth_mode_id" name="auth_mode_id" value="<?=  BBBManager_Config_Defines::$LOCAL_AUTH_MODE;?>" />
    <? endif; ?>
    
    <div class="control-group">
        <label class="control-label" for="name"><?=$this->translate('column-user-name'); ?></label>
        <div class="controls">
            <input type="text" id="name" name="name" value="">
        </div>
    </div>
    
    <div class="control-group">
        <label class="control-label" for="login"><?=$this->translate('column-user-login'); ?></label>
        <div class="controls">
            <? if(Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'new'): ?>
                <?= (isset($this->new_user_prefix)) ? $this->new_user_prefix : ''; ?><input type="text" id="login" name="login" value="">
            <? elseif(IMDT_Util_Auth::getInstance()->get('user_access_profile') == BBBManager_Config_Defines::$SYSTEM_PRIVILEGED_USER_PROFILE): ?>
                <input type="text" id="login" name="login" value="" disabled="disabled" readonly="readonly">
            <? else: ?>
                <input type="text" id="login" name="login" value="">
            <? endif; ?>
            
        </div>
    </div>
    
    <div class="control-group">
        <label class="control-label" for="email"><?=$this->translate('column-user-email'); ?></label>
        <div class="controls">
            <input type="text" id="email" name="email" value="">
        </div>
    </div>
	
    <?
	if($this->id == 'new'):
    ?>
    <div class="control-group">
        <div class="controls">
	    <label class="checkbox" for="send_password"><?=$this->translate('Send password by email'); ?>
		<input type="checkbox" id="send_password" name="send_password" value="1" <?=(IMDT_Util_Config::getInstance()->get('users_management_send_password_on_add') == '1') ? ' checked="checked"' : ''?>>
	    </label>
        </div>
    </div>
    <?
	endif;
    ?>
    
    <? if($this->id != 'new'): ?>
    <div class="control-group">
        <label class="control-label" for="access_profile_id"><?=$this->translate('column-user-access_profile_id'); ?></label>
        <div class="controls">
            <input type="text" id="access_profile_name" name="access_profile_name" class="span6" disabled="disabled"/>
        </div>
    </div>
    <? endif; ?>
    
    <div class="control-group">
        <label class="control-label" for="groups"><?=$this->translate('column-user-groups'); ?></label>
        <div class="controls">
            <? if(IMDT_Util_Auth::getInstance()->get('user_access_profile') == BBBManager_Config_Defines::$SYSTEM_PRIVILEGED_USER_PROFILE): ?>
                <input type="hidden" id="groups" name="groups" class="span6 select2 multiple" source="group" disabled="disabled" readonly="readonly" />
            <? else: ?>
                <input type="hidden" id="groups" name="groups" class="span6 select2 multiple" source="group" onChange="$('#btnExportCsvGroups').addClass('disabled').removeAttr('href');" />
            <? endif; ?>
            
            <? if($this->id != 'new'): ?>
                <a id="btnExportCsvGroups" class="btn" style="margin-left:8px;" href="<?=$this->url(array('action'=>'export-groups'));?>"><?=$this->translate('Export CSV'); ?></a>
            <? endif; ?>
        </div>
    </div>
    
    <div class="control-group">
        <label class="control-label" for="valid_from"><?=$this->translate('column-user-valid_from'); ?></label>
        <div class="controls">
            <div class="input-append datepick">
                <input type="text" id="valid_from" name="valid_from" class="input-block-level" data-format="<?=$this->translate('dateFormat-datepicker'); ?>"/>
                <span class="add-on"><i data-date-icon="icon-calendar"></i></span>
            </div>
            <br />
            <span class="input-observation"><?=$this->translate('Date from which will be able to login with this user, if not filled start date will not be restricted'); ?></span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="valid_to"><?=$this->translate('column-user-valid_to'); ?></label>
        <div class="controls">
            <div class="input-append datepick">
                <input type="text" id="valid_to" name="valid_to" class="input-block-level" data-format="<?=$this->translate('dateFormat-datepicker'); ?>"/>
                <span class="add-on"><i data-date-icon="icon-calendar"></i></span>
            </div>
            <br />
            <span class="input-observation"><?=$this->translate('Date from which will not be able to login with this user, if not filled start end will not be restricted'); ?></span>
        </div>
    </div>
    
    <div class="control-group">
        <label class="control-label" for="observations"><?=$this->translate('column-user-observations'); ?> </label>
        <div class="controls">
            <textarea class="span6 autosize" id="observations" name="observations"></textarea>
        </div>
    </div>
    
    <div class="form-actions">
            <button type="submit" class="btn btn-primary"><?=$this->translate('Save'); ?></button>
            <? if($this->id != 'new'): ?>
                <a class="btn" href="#" open-modal-form="#resetPassword" form-data=''><?=$this->translate('Reset password'); ?></a>
            <? endif; ?>
            <a class="btn" href="<?=$this->url(array('action'=>'index','id'=>null)); ?>"><?=$this->translate('Cancel'); ?></a>
        </div>
</form>


<div id="resetPassword" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <form id="form-invite" class="form-horizontal no-loading no-reset" action="<?=$this->url(array('action'=>'post-reset-password'));?>">
        <input type="hidden" name="user_id" id="user_id" value="<?=$this->id;?>" />
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel"><?=$this->translate('Reset password'); ?></h3>
        </div>
        <div class="modal-body">
            <span><?=$this->translate('A new password will be sent by e-mail.'); ?></span>
        </div>
        
        <div class="modal-footer">
            <div class="hide alert alert-error" style="text-align:center;"><?=$this->translate('Alert'); ?></div>
            <span class="save-buttons">
                <button type="submit" class="btn btn-primary"><?=$this->translate('Confirm'); ?></button>
                <button class="btn" data-dismiss="modal" aria-hidden="true"><?=$this->translate('Close'); ?></button>
            </span>
            <span class="success-buttons hide">
                <div class="alert alert-success" style="text-align:center;"></div>
                <button class="btn" data-dismiss="modal" aria-hidden="true"><?=$this->translate('Close'); ?></button>
            </span>
            <span class="loading hide">
                <div style="text-align:center;"><?=$this->translate('Saving'); ?></div>
                <div class="progress progress-striped active"><div class="bar" style="width: 100%;"></div></div>
            </span>
        </div>
    </form>
</div>