<a href="<?= $this->url(array('action' => 'index', 'id' => null)); ?>"><?= $this->controllerTitle; ?></a> / <h4><?= $this->title; ?></h4>

<form id="formEdit" class="form-horizontal ajaxsubmit" source="<?=$this->url(array('action'=>'form-content','id'=>$this->id));?>">

    <div class="control-group">
	<label class="control-label" for="access_profile_id"><?= $this->translate('column-user-auth_mode_id'); ?></label>
	<div class="controls">
	    <input type="hidden" id="auth_mode_id" name="auth_mode_id" class="span6 select2" source="auth_mode" disabled="disabled" readonly="readonly" />
	</div>
    </div>

    <div class="control-group">
        <label class="control-label" for="name"><?= $this->translate('column-user-name'); ?></label>
        <div class="controls">
            <input type="text" id="name" name="name" value="" disabled="disabled" readonly="readonly" />
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="login"><?= $this->translate('column-user-login'); ?></label>
        <div class="controls">
            <input type="text" id="login" name="login" value="" disabled="disabled" readonly="readonly" />
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="email"><?= $this->translate('column-user-email'); ?></label>
        <div class="controls">
            <input type="text" id="email" name="email" value="" disabled="disabled" readonly="readonly" readonly="readonly" disabled="disabled"/>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="access_profile_id"><?= $this->translate('column-user-access_profile_id'); ?></label>
        <div class="controls">
            <input type="text" id="access_profile_name" name="access_profile_name" class="span6" disabled="disabled"/>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="groups"><?= $this->translate('column-user-groups'); ?></label>
        <div class="controls">
            <input type="hidden" id="groups" name="groups" class="span6 select2 multiple" source="group" readonly="readonly" disabled="disabled" />
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="groups"><?= $this->translate('LDAP Groups'); ?></label>
        <div class="controls">
            <input type="hidden" id="ldapGroups" name="ldapGroups" class="span6 select2 multiple" source="ldapGroup" readonly="readonly" disabled="disabled"/>
        </div>
    </div>
    
    <div class="control-group">
        <label class="control-label" for="groups"><?=$this->translate('column-user-actived'); ?></label>
        <div class="controls">
            <input type="text" id="actived" name="actived" class="span2" source="actived" readonly="readonly" disabled="disabled"/>
        </div>
    </div>

    <div class="form-actions">
	<a class="btn" href="<?= $this->url(array('action' => 'index', 'id' => null)); ?>"><?= $this->translate('Back'); ?></a>
    </div>
</form>