<?
    $name = $this->currParam['n'];
?>
    
            <? if($this->paramOptions['type'] == 'text'): ?>
                <div class="filter-values <?=$this->paramName;?> <?= ($this->paramName == $name) ? '' : 'hide'; ?>">
                    <? $value = ($this->paramName == $name) ? $this->currParam['v'] : ''; ?>
                    <? $conditionValue = ($this->paramName == $name) ? $this->currParam['c'] : ''; ?>
                    <div class="span2" style="margin-left:0px">
                        <select class="condition">
                            <option value="in" class="" <?= ($conditionValue == 'in') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-text-in'); ?></option>
                            <option value="nin" class="" <?= ($conditionValue == 'nin') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-text-nin'); ?></option>
                            <option value="is" class="" <?= ($conditionValue == 'is') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-text-is'); ?></option>
                            <option value="isnt" class="" <?= ($conditionValue == 'isnt') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-text-isnt'); ?></option>
                            <option value="bw" class="" <?= ($conditionValue == 'bw') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-text-bw'); ?></option>
                            <option value="ew" class="" <?= ($conditionValue == 'ew') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-text-ew'); ?></option>
                            <option value="empty" class="" <?= ($conditionValue == 'empty') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-text-empty'); ?></option>
                            <option value="nempty" class="" <?= ($conditionValue == 'nempty') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-text-nempty'); ?></option>
                        </select>
                    </div>
                    <div class="span2" style="margin-left:0px">
                        <div class="input-append">
                            <input type="text" class="small-input value" value="<?= $value; ?>" />
                        </div>
                    </div>
                </div>
            <? endif; ?>
            
            <? if($this->paramOptions['type'] == 'date'): ?>
                <div class="filter-values <?=$this->paramName;?>  <?= ($this->paramName == $name) ? '' : 'hide'; ?>">
                    <? $value = ($this->paramName == $name && !empty($this->currParam['v'])) ? IMDT_Util_Date::filterDateToCurrentLang($this->currParam['v']) : ''; ?>
                    <? $conditionValue = ($this->paramName == $name && !empty($this->currParam['c'])) ? $this->currParam['c'] : ''; ?>
                    <div class="span2" style="margin-left:0px">
                        <select class="condition">
                            <option value="is" class="" <?= ($conditionValue == 'is') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-date-is'); ?></option>
                            <option value="isnt" class="" <?= ($conditionValue == 'isnt') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-date-isnt'); ?></option>
                            <option value="bef" class="" <?= ($conditionValue == 'bef') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-date-bef'); ?></option>
                            <option value="aft" class="" <?= ($conditionValue == 'aft') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-date-aft'); ?></option>
                            <option value="empty" class="" <?= ($conditionValue == 'empty') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-date-empty'); ?></option>
                            <option value="nempty" class="" <?= ($conditionValue == 'nempty') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-date-nempty'); ?></option>
                        </select>
                    </div>
                    <div class="span2" style="margin-left:0px">
                        <div class="input-append datepick">
                            <input type="text" class="input-block-level value" data-format="<?=$this->translate('dateFormat-datepicker'); ?>"  value="<?=$value; ?>">
                            <span class="add-on"><i data-time-icon="icon-time" data-date-icon="icon-calendar"></i></span>
                        </div>
                    </div>
                </div>
            <? endif; ?>
            
            <? if($this->paramOptions['type'] == 'datetime'): ?>
                <div class="filter-values <?=$this->paramName;?>  <?= ($this->paramName == $name) ? '' : 'hide'; ?>">
                    <? $value = ($this->paramName == $name && !empty($this->currParam['v'])) ? IMDT_Util_Date::filterDatetimeToCurrentLang($this->currParam['v']) : ''; ?>
                    <? $conditionValue = ($this->paramName == $name && !empty($this->currParam['c'])) ? $this->currParam['c'] : ''; ?>
                    <div class="span2" style="margin-left:0px">
                        <select class="condition">
                            <option value="is" class="" <?= ($conditionValue == 'is') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-datetime-is'); ?></option>
                            <option value="isnt" class="" <?= ($conditionValue == 'isnt') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-datetime-isnt'); ?></option>
                            <option value="bef" class="" <?= ($conditionValue == 'bef') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-datetime-bef'); ?></option>
                            <option value="aft" class="" <?= ($conditionValue == 'aft') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-datetime-aft'); ?></option>
                            <option value="empty" class="" <?= ($conditionValue == 'empty') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-datetime-empty'); ?></option>
                            <option value="nempty" class="" <?= ($conditionValue == 'nempty') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-datetime-nempty'); ?></option>
                        </select>
                    </div>
                    <div class="span2" style="margin-left:0px">
                        <div class="input-append datetime">
                            <input type="text" class="input-block-level value" data-format="<?=$this->translate('dateFormat-datepicker'); ?> hh:mm"  value="<?=$value; ?>">
                            <span class="add-on"><i data-time-icon="icon-time" data-date-icon="icon-calendar"></i></span>
                        </div>
                    </div>
                </div>
            <? endif; ?>
            
            <? if($this->paramOptions['type'] == 'ipaddress'): ?>
                <div class="filter-values <?=$this->paramName;?> <?= ($this->paramName == $name) ? '' : 'hide'; ?>">
                    <? $value = ($this->paramName == $name) ? $this->currParam['v'] : ''; ?>
                    <? $conditionValue = ($this->paramName == $name) ? $this->currParam['c'] : ''; ?>
                    <div class="span2" style="margin-left:0px">
                        <select class="condition">
                            <option value="in" class="" <?= ($conditionValue == 'in') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-text-in'); ?></option>
                            <option value="nin" class="" <?= ($conditionValue == 'nin') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-text-nin'); ?></option>
                            <option value="is" class="" <?= ($conditionValue == 'is') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-text-is'); ?></option>
                            <option value="isnt" class="" <?= ($conditionValue == 'isnt') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-text-isnt'); ?></option>
                            <option value="bw" class="" <?= ($conditionValue == 'bw') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-text-bw'); ?></option>
                            <option value="ew" class="" <?= ($conditionValue == 'ew') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-text-ew'); ?></option>
                            <option value="empty" class="" <?= ($conditionValue == 'empty') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-text-empty'); ?></option>
                            <option value="nempty" class="" <?= ($conditionValue == 'nempty') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-text-nempty'); ?></option>
                        </select>
                    </div>
                    
                    <div class="span2" style="margin-left:0px">
                        <div class="input-append">
                            <input type="text" class="small-input value ipaddress" value="<?= $value; ?>" placeholder="xxx.xxx.xxx.xxx" />
                        </div>
                    </div>
                </div>
            <? endif; ?>
            
            <? if($this->paramOptions['type'] == 'combo'): ?>
                <div class="filter-values <?=$this->paramName;?> <?= ($this->paramName == $name) ? '' : 'hide'; ?>">
                    <? $value = ($this->paramName == $name) ? $this->currParam['v'] : ''; ?>
                    <? $conditionValue = ($this->paramName == $name) ? $this->currParam['c'] : ''; ?>
                    <? $source = (isset($this->paramOptions['source'])) ? $this->paramOptions['source'] : ''; ?>
                    <div class="span2" style="margin-left:0px">
                        <select class="condition">
                            <option value="is" class="" <?= ($conditionValue == 'is') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-combo-is'); ?></option>
                            <option value="isnt" class="" <?= ($conditionValue == 'isnt') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-combo-isnt'); ?></option>
                            <option value="empty" class="" <?= ($conditionValue == 'empty') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-combo-empty'); ?></option>
                            <option value="nempty" class="" <?= ($conditionValue == 'nempty') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-combo-nempty'); ?></option>
                        </select>
                    </div>
                    
                    <div class="span2" style="margin-left:0px">
                        <div class="input-append">
                            <select class="select2 value span6" source="<?=$source;?>" multiple="multiple" style="width:80%;" data-value="<?= $value; ?>">
                            </select>
                        </div>
                    </div>
                </div>
            <? endif; ?>
            
            <? if($this->paramOptions['type'] == 'combo-remote'): ?>
                <div class="filter-values <?=$this->paramName;?> <?= ($this->paramName == $name) ? '' : 'hide'; ?>">
                    <? $value = ($this->paramName == $name) ? $this->currParam['v'] : ''; ?>
                    <? $conditionValue = ($this->paramName == $name) ? $this->currParam['c'] : ''; ?>
                    <? $source = (isset($this->paramOptions['source'])) ? $this->paramOptions['source'] : ''; ?>
                    <div class="span2" style="margin-left:0px">
                        <select class="condition">
                            <option value="is" class="" <?= ($conditionValue == 'is') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-combo-is'); ?></option>
                            <option value="isnt" class="" <?= ($conditionValue == 'isnt') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-combo-isnt'); ?></option>
                            <option value="empty" class="" <?= ($conditionValue == 'empty') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-combo-empty'); ?></option>
                            <option value="nempty" class="" <?= ($conditionValue == 'nempty') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-combo-nempty'); ?></option>
                        </select>
                    </div>
                    
                    <div class="span2" style="margin-left:0px">
                        <div class="input-append">
                            <input type="hidden" style="width:80%;" value="<?= $value; ?>" id="user_attendee" name="user_attendee" class="span6 value select2 multiple" remote="<?=$this->url($this->paramOptions['url']);?>" />
                        </div>
                    </div>
                </div>
            <? endif; ?>
            
            
            <? if($this->paramOptions['type'] == 'integer'): ?>
                <div class="filter-values <?=$this->paramName;?> <?= ($this->paramName == $name) ? '' : 'hide'; ?>">
                    <? $value = ($this->paramName == $name) ? $this->currParam['v'] : ''; ?>
                    <? $conditionValue = ($this->paramName == $name) ? $this->currParam['c'] : ''; ?>
                    <div class="span2" style="margin-left:0px">
                        <select class="condition">
                            <option value="is" class="equal" <?= ($conditionValue == 'is') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-integer-is'); ?></option>
                            <option value="isnt" class="equal" <?= ($conditionValue == 'isnt') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-integer-isnt'); ?></option>
                            <option value="gt" class="greater" <?= ($conditionValue == 'gt') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-integer-gt'); ?></option>
                            <option value="lt" class="less" <?= ($conditionValue == 'lt') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-integer-lt'); ?></option>
                            <option value="empty" class="" <?= ($conditionValue == 'empty') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-integer-empty'); ?></option>
                            <option value="nempty" class="" <?= ($conditionValue == 'nempty') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-integer-nempty'); ?></option>
                        </select>
                    </div>
                    <div class="span2" style="margin-left:0px">
                        <div class="input-append">
                            <input type="text" class="small-input value integer" value="<?= $value; ?>" />
                        </div>
                    </div>
                </div>
            <? endif; ?>
            
            <? if($this->paramOptions['type'] == 'boolean'): ?>
                <div class="filter-values <?=$this->paramName;?> <?= ($this->paramName == $name) ? '' : 'hide'; ?>">
                    <? $value = ($this->paramName == $name) ? $this->currParam['v'] : ''; ?>
                    <? $conditionValue = ($this->paramName == $name) ? $this->currParam['c'] : ''; ?>
                    <div class="span2" style="margin-left:0px">
                        <select class="condition">
                            <option value="is" class="equal" <?= ($conditionValue == 'is') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-bool-is'); ?></option>
                            <option value="empty" class="" <?= ($conditionValue == 'empty') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-bool-empty'); ?></option>
                            <option value="nempty" class="" <?= ($conditionValue == 'nempty') ? 'selected="selected"' : ''; ?>><?=$this->translate('advs-bool-nempty'); ?></option>
                        </select>
                    </div>
                    
                    <div class="span2" style="margin-left:0px">
                        <div class="input-append">
                            <select class="value span6" style="width:80%;">
                                <option value=""></option>
                                <option value="1" <?= ($value == '1') ? 'selected="selected"' : ''; ?>><?=$this->translate('Yes'); ?></option>
                                <option value="0" <?= ($value == '0') ? 'selected="selected"' : ''; ?>><?=$this->translate('No'); ?></option>
                            </select>
                        </div>
                    </div>
                </div>
            <? endif; ?>
            