<div class="accordion" id="accordion2">
    <?
	$roomAccess = (isset($this->allowedMenuItens[BBBManager_Config_Defines::$ACL_MY_ROOMS_RESOURCE]) ? true : false);
	$groups = (isset($this->allowedMenuItens[BBBManager_Config_Defines::$ACL_GROUP_RESOURCE]) ? true : false);
	$speedProfiles = (isset($this->allowedMenuItens[BBBManager_Config_Defines::$ACL_SPEED_PROFILES_RESOURCE]) ? true : false);
	$tags = (isset($this->allowedMenuItens[BBBManager_Config_Defines::$ACL_TAG_RESOURCE]) ? true : false);
	$users = (isset($this->allowedMenuItens[BBBManager_Config_Defines::$ACL_USER_RESOURCE]) ? true : false);
	$rooms = (isset($this->allowedMenuItens[BBBManager_Config_Defines::$ACL_ROOM_RESOURCE]) ? true : false);
	$roomCategories = (isset($this->allowedMenuItens[BBBManager_Config_Defines::$ACL_CATEGORY_RESOURCE]) ? true : false);
        $accessLogs = (isset($this->allowedMenuItens[BBBManager_Config_Defines::$ACL_ACCESS_LOGS_RESOURCE]) ? true : false);
	$inviteTemplates = (isset($this->allowedMenuItens[BBBManager_Config_Defines::$ACL_INVITE_TEMPLATE_RESOURCE]) ? true : false);
	$maintenanceMode = (isset($this->allowedMenuItens[BBBManager_Config_Defines::$ACL_MAINTENANCE_RESOURCE]) ? true : false);
    ?>
    <?
	if($roomAccess):
    ?>
    <div class="accordion-group">
      <div class="accordion-heading">
	<a class="accordion-toggle" data-parent="#accordion2" <a href="/ui/my-rooms"><?= $this->translate('Meeting Rooms Access'); ?></a>
      </div>
    </div>
    <?
	endif;
    ?>
    <?
	if($groups):
    ?>
    <div class="accordion-group">
      <div class="accordion-heading">
	<a class="accordion-toggle" data-parent="#accordion2" href="/ui/groups">
	    <?= $this->translate('Groups'); ?>
	</a>
      </div>
    </div>
    <?
	endif;
    ?>
    <?
	if($speedProfiles):
    ?>
    <div class="accordion-group">
      <div class="accordion-heading">
	<a class="accordion-toggle" data-parent="#accordion2" href="/ui/speed-profiles">
	    <?= $this->translate('Speed Profiles'); ?>
	</a>
      </div>
    </div>
    <?
	endif;
    ?>
    <?
	if($rooms):
    ?>
    <div class="accordion-group">
      <div class="accordion-heading">
	<a class="accordion-toggle" data-parent="#accordion2" <a href="/ui/rooms/index"><?= $this->translate('Meeting Rooms'); ?></a>
      </div>
    </div>
    <?
	endif;
    ?>
    <?
	if($roomCategories || $inviteTemplates || $maintenanceMode || $accessLogs):
    ?>
    <div class="accordion-group">
      <div class="accordion-heading">
	<a class="accordion-toggle filhos" data-toggle="collapse" data-parent="#accordion2" href="#collapseAdm">
	  <?= $this->translate('System'); ?><i class="icon-chevron-right pull-right"></i>
	</a>
      </div>
      <div id="collapseAdm" class="accordion-body collapse">
	<div class="accordion-inner">
	    <ul class="nav nav-list">
		<?
		    if($roomCategories):
		?>
		<li <?=(in_array($this->currentUrl, array('/ui/categories/index')) ? ' class="active"' : '');?>><a href="/ui/categories"><?= $this->translate('Categories'); ?></a></li>
		<?
		    endif;
		?>
		<?
		    if($accessLogs):
		?>
		<li <?=(in_array($this->currentUrl, array('/ui/access-logs/index')) ? ' class="active"' : '');?>><a href="/ui/access-logs/index"><?= $this->translate('Access Logs'); ?></a></li>
		<?
		    endif;
		?>
		<?
		    if($inviteTemplates):
		?>
		<li <?=(in_array($this->currentUrl, array('/ui/invite-templates/index')) ? ' class="active"' : '');?>><a href="/ui/invite-templates/index"><?= $this->translate('Invite Templates'); ?></a></li>
		<?
		    endif;
		?>
		<?
		    if($maintenanceMode):
		?>
		<li <?=(in_array($this->currentUrl, array('/ui/maintenance/index')) ? ' class="active"' : '');?>><a href="/ui/maintenance/index"><?= $this->translate('Maintenance Mode'); ?></a></li>
		<?
		    endif;
		?>
		<?
		    if(false):
		?>
		<li <?=(in_array($this->currentUrl, array('/ui/skinning/index')) ? ' class="active"' : '');?>><a href="/ui/skinning/index"><?= $this->translate('Skinning'); ?></a></li>
		<?
		    endif;
		?>
	    </ul>
	</div>
      </div>
    </div>
    <?
	endif;
    ?>
    <?
	if($users):
    ?>
    <div class="accordion-group">
      <div class="accordion-heading">
	<a class="accordion-toggle" data-parent="#accordion2" href="/ui/users/index">
	  <?= $this->translate('Users'); ?>
	</a>
      </div>
    </div>
    <?
	endif;
    ?>
</div>