<h4>Categorias</h4>
<div class="pull-left">
    <a href="#" onclick="adicionarCategoria('null');return false;" class="btn"><i class="icon-plus-sign"></i> Nova Categoria Raiz</a>
    <button class="btn" id="excluirSelecionados"><i class="icon-trash"></i> Excluir Selecionados</button>
    <a class="btn" id="selecionarTodos"><i class="icon-ok"></i> Selecionar Todos</a>
</div>

<div class="pull-right">
    <div class="input-append pull-right">
        <input type="text" id="buscaCategorias">
    </div>
</div>

<table class="table table-striped" id="tblTree">
    <thead>
        <tr>                
            <th>#</th>
            <th>Categoria</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?
        if (!empty($this->arrCategorias)):
            foreach ($this->arrCategorias as $categoria):
                echo $this->partial('categories/row.phtml', array('item'=>$categoria));
            endforeach;
        else:
        ?>
            <tr>
                <td colspan="3">Nenhum registro encontrado.</td>
            </tr>
        <? endif; ?>
    </tbody>
</table>

<div class="row-fluid">
    <div class="span12 pull-left">
        <div class="btn-group">
            <button class="btn">Exportar</button>
            <button class="btn dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li><a href="#">CSV</a></li>
                <li><a href="#">PDF</a></li>
            </ul>
        </div>
        <button class="btn">Importar CSV</button>
    </div>
</div>

<div id="modalCategory" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Nova Categoria</h3>
    </div>
    <div class="modal-body">
        <div class="control-group">
            <label class="control-label">Nome</label>
            <input type="text" class="input-block-level" id="catName" />
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btn-primary" aria-hidden="true" id="addBtn">Adicionar</button>
        <button class="btn " data-dismiss="modal" aria-hidden="true">Fechar</button>
    </div>
</div>

<script>
    nomesCategorias = <?=json_encode($this->nomeCategorias);?>;
</script>